FROM arm32v7/python:3.7-slim-buster

WORKDIR /app

RUN apt-get update && apt-get -y upgrade && apt-get -y install python3-smbus && apt-get -y install i2c-tools && apt-get -y install cmake

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]